### ISSUE TITLE
Ionic 3 / detectChanges()

### ISSUE THREAD

**Issue by ghost** [mgnstudio7/stenciljs-virtual-scroll#4]
Hi!
congratulations on your work, this virtual-scroll looks well done.

I was trying to make it work with ionic 3. 
I have this issue: the event "toBottom" is never trigged.
I saw this commented function ( //this.changeDetector.detectChanges(); ) but I don't know how to use it. Can you help me with an example?

**Comment by mgnstudio7** [comment]
@andreandev hi, thanks for using and your review.
Maybe event "toBottom" not called, because component virtual-scroll not attached to scrollable container. In your case it is ```<ion-content>```(for Ionic2+)

Set in selector attribute ion-content class value.
Example (class="about-page"):

```html
...
<ion-content no-padding class="about-page">
...
<virtual-scroll #scroll bottom-offset="5" virtual-ratio="5" selector="about-page .scroll-content">
...
```
https://github.com/mgnstudio7/ionic-virtual-scroll-example/blob/master/src/pages/about/about.html

If this solution did not help you, I'll need an example of your code.

**Comment by ghost** [comment]
@mgnstudio7 thanks, it works!

**Comment by ghost** [comment]
One question @mgnstudio7.
If I load the results all at once, can I use the virtual scroll without the "toBottom" event?
Have you ever tried? Thanks!

**Comment by mgnstudio7** [comment]
@andreandev 
Yes. If you don't use lazy load, you don't need subscribe on "toBottom" event. 
But, you still need to attach virtual-scroll to scrollable container, for correct virtual-list work.

**Comment by ghost** [comment]
Ok I'll try what you said. Thanks again.
